spring.application.name=user-product-api


# MongoDB Configuration
spring.data.mongodb.uri=mongodb://localhost:27017/userproductdb
spring.data.mongodb.database=userproductdb

# Server Configuration
server.port=8088

# Logging
logging.level.org.springframework.data.mongodb=DEBUG
logging.level.com.example.userproductapi=DEBUG
